Pierres/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace Pierres.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    [Required(ErrorMessage = "No treats have been added!")]
    public string TreatType { get; set; }
    public Flavor Flavor { get; set; }
    public List<TreatFlavor> JoinTreat { get; }
    public ApplicationUser User { get; set; } 
  }
}

Pierres/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Pierres.Models;
using System.Threading.Tasks;
using Pierres.ViewModels;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace Pierres.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresContext _db;

    public TreatsController(PierresContext db)
    {
      _db = db;
    }

    [AllowAnonymous]
     public ActionResult Index()
    {
      List<Treat> model = _db.Treats
                              .Include(treat => treat.Flavor)
                              .ToList();
      return View(model);
    }

     public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }


    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Treat thisTreat = _db.Treats
        .Include(treat => treat.JoinTreat)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorType");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Treats.Update(treat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

     public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treats => treats.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "FlavorType");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddEngineer(Treat treat, int flavorId)
    {
      #nullable enable
      TreatFlavor? joinEntity = _db.TreatFlavors.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
      #nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.TreatFlavors.Add(new TreatFlavor() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [HttpPost]
    public ActionResult DeleteJoinTreat (int joinId)
    {
      TreatFlavor joinEntry = _db.TreatFlavors.FirstOrDefault(entry => entry.TreatFlavorId == joinId);
      _db.TreatFlavors.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Pierres/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}


@model Pierres.Models.Treat

<h2>Add a Treat</h2>

<h4>Flavor to the Treat: @Html.DisplayFor(model => model.TreatType)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.TreatId)

    @Html.Label("Select flavor")
    @Html.DropDownList("FlavorId")

    <input type="submit" value="Save" />
}

Pierres/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model Pierres.Models.Treat

<h4>Add a new Treat</h4>
<p>@Html.ValidationMessageFor(model => model.TreatType, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.TreatType)
  @Html.TextBoxFor(model => model.TreatType, new { required="required" })

  <input type="submit" value="Add new Treat" class="btn btn-primary"/>
}

Pierres/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Pierres.Models.Treat

<h2>Are you sure you want to delete this Treat?</h2>

@Html.DisplayNameFor(model => model.TreatType): @Html.DisplayFor(model => model.TreatType)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

Pierres/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using Pierres.Models
@model Pierres.Models.Treat

<h2>Treat Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.TreatType): @Html.DisplayFor(model => model.TreatType)</h3>  

@if(Model.JoinTreat.Count == 0)
{
  <p>This Treat has no Flavors!</p>
}
else
{
  <h4>Flavors for this Treat:</h4>
  
  @foreach(TreatFlavor join in Model.JoinTreat)
  {
    <p>@join.Flavor.FlavorType</p>

    @using (Html.BeginForm("DeleteJoin", "Treats"))
    {
      @Html.Hidden("joinId", @join.TreatFlavorId)
      <input type="submit" value="Delete"/>
    }
  }
}


<div id="index-nav">
<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId }) | @Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Add a Flavor", "AddFlavor", new { id = Model.TreatId })
</div>

Pierres/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Pierres.Models.Treat

<h2>Edit</h2>

<h4>Edit this Treat: @Html.DisplayFor(model => model.TreatType)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.TreatType)
  @Html.EditorFor(model => model.TreatType)


  <input type="submit" value="Save" />
}

Pierres/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using Pierres.Models;

<h1>Treats</h1>

@if (@Model.Count == 0)
{
  <h3>No Treats have been added!</h3>
} 
else
{

@foreach (Treat treat in Model)
  {
    <p>@Html.ActionLink($"{treat.TreatType}", "Details", new { id = treat.TreatId })</p>
  }
}

<div id="index-nav">
<p>@Html.ActionLink("Add new Treat", "Create")</p>
</div>